apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-envoy-deployment
  namespace: {{ .Values.global.namespace}}
  labels:
    component: metadata-envoy
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: metadata-envoy
  template:
    metadata:
      labels:
        component: metadata-envoy
        application-crd-id: {{ .Values.global.labels.applicationCrdId }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: container
        image: "{{ .Values.images.name }}:{{ .Values.images.newTag }}"
        ports:
        - name: md-envoy
          containerPort: 9090
        - name: envoy-admin
          containerPort: 9901
