apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-pipelines-cache-deployer-sa
  labels:
    app.kubernetes.io/component: {{ .Values.labels.appKubernetesIoComponent }}
    app.kubernetes.io/name: {{ .Values.labels.appKubernetesIoName }}
  namespace: {{ .Values.namespace}}