apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-pipelines-container-builder
  namespace: {{ .Values.global.namespace}}
  labels:
    app.kubernetes.io/name: {{ .Values.global.labels.appKubernetesIoName }}
    app.kubernetes.io/component: {{ .Values.global.labels.appKubernetesIoComponent }}
