apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.global.labels.appKubernetesIoName }}
    app.kubernetes.io/component: {{ .Values.global.labels.appKubernetesIoComponent }}
  name: pipeline-runner-binding
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-runner
subjects:
- kind: ServiceAccount
  name: pipeline-runner
  namespace: {{ .Values.global.namespace }}
