apiVersion: v1
data:
  viewer-pod-template.json: |-
    {
        "spec": {
            "serviceAccountName": "default-editor"
        }
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.labels.appKubernetesIoName }}
    app.kubernetes.io/component: {{ .Values.labels.appKubernetesIoComponent }}
  name: ml-pipeline-ui-configmap
  namespace: kubeflow