apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: /argo
  name: argo
  labels:
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
  namespace: {{ .Values.global.namespace }}