kind: Service
apiVersion: v1
metadata:
  labels:
    app: metadata
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
  name: metadata-grpc-service
  namespace: {{ .Values.global.namespace}}
spec:
  selector:
    component: metadata-grpc-server
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    name: grpc-api
