kind: Service
apiVersion: v1
metadata:
  labels:
    app: metadata-envoy
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
  name: metadata-envoy-service
  namespace: {{ .Values.global.namespace}}
spec:
  selector:
    component: metadata-envoy
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
  type: ClusterIP
  ports:
  - port: 9090
    protocol: TCP
    name: md-envoy
