apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ml-pipeline-viewer-crd-binding
  labels:
    app.kubernetes.io/name: {{ .Values.labels.appKubernetesIoName }}
    app.kubernetes.io/component: {{ .Values.labels.appKubernetesIoComponent }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ml-pipeline-viewer-controller-role
subjects:
- kind: ServiceAccount
  name: ml-pipeline-viewer-crd-service-account
