apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.global.labels.appKubernetesIoName }}
    app.kubernetes.io/component: {{ .Values.global.labels.appKubernetesIoComponent }}
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
    app: metadata-writer
  name: metadata-writer
  namespace: {{ .Values.global.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-writer
      app.kubernetes.io/name: {{ .Values.global.labels.appKubernetesIoName }}
      app.kubernetes.io/component: {{ .Values.global.labels.appKubernetesIoComponent }}
      application-crd-id: {{ .Values.global.labels.applicationCrdId }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.global.labels.appKubernetesIoName }}
        app.kubernetes.io/component: {{ .Values.global.labels.appKubernetesIoComponent }}
        application-crd-id: {{ .Values.global.labels.applicationCrdId }}
        app: metadata-writer 
    spec:
      containers:
      - name: main
        image: "{{ .Values.images.name }}:{{ .Values.images.newTag }}"
        env:
        - name: NAMESPACE_TO_WATCH
          value: {{ .Values.spec.containers.env.value }}
      serviceAccountName: kubeflow-pipelines-metadata-writer
