apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ml-pipeline-persistenceagent-role
  labels:
    app.kubernetes.io/name: {{ .Values.labels.appKubernetesIoName }}
    app.kubernetes.io/component: {{ .Values.labels.appKubernetesIoComponent }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - scheduledworkflows
  verbs:
  - get
  - list
  - watch
