apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ml-pipeline-viewer-controller-role
  labels:
    app.kubernetes.io/name: {{ .Values.global.labels.appKubernetesIoName }}
    app.kubernetes.io/component: {{ .Values.global.labels.appKubernetesIoComponent }}
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  - services
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - kubeflow.org
  resources:
  - viewers
  - viewers/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
