apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: metadata-grpc-service
  namespace: {{ .Values.global.namespace }}
  labels:
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
spec:
  host: metadata-grpc-service.kubeflow.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
