apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: metadata-grpc-service
  labels:
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
  namespace: {{ .Values.global.namespace }}
spec:
  action: ALLOW
  rules:
  - {}
  selector:
    matchLabels:
      component: metadata-grpc-server
