apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: metadata-grpc-service
spec:
  action: ALLOW
  selector:
    matchLabels:
      component: metadata-grpc-server
      application-crd-id: {{ .Values.global.labels.applicationCrdId }}
  rules:
  - {}
