apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: {{ .Values.global.namespace }}
  labels:
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
    application-crd-id: {{ .Values.global.labels.applicationCrdId }}
